### ISSUE TITLE
Incorrect team hashing implementation

### ISSUE THREAD

**Issue by repnox** [Bauloewe/SMBotFramework#1]
https://github.com/Bauloewe/SMBotFramework/blob/b4dc2c62c240a76743ed93d57748cc21784d8b52/Requests.py#L78

Monster UIDs are concatenated, not joined with a comma.

Proof: Check the official SM.min.js
var team_hash = md5(summoner + "," + monsters.join() + "," + secret);

**Comment by Bauloewe** [comment]
Hi repnox, 

thank for pointing that out,

correct me if I'm wrong, but javascripts array function join() concatenates the entries of the array with a comma by default. Edit: W3C doc https://www.w3schools.com/jsref/jsref_join.asp "Any separator can be specified. The default is comma (,)."

Did a quick test as well: 

let test = ["a","b"]
console.log(test.join())
=> a,b

Are there any issues with the md5 hash when submitting matches?
I haven't looked at the game nor the framework in a couple months.
But I'll look over the codebase within the coming weeks and overhaul it. that should turn it into a more maintainable code base. Because as of now its a mess (:.
